### ISSUE TITLE
Cannot authenticate to Fossil servers; certificate error 

### ISSUE THREAD

**Issue by buttnose** [dakhnod/WatchAuthenticator#5]
As of this week, I am unable to connect to the Fossil servers - I receive the error below:

**auth error: Unacceptable certificate: CN=DigiCert High Assurance EV Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US**

![Screenshot_20240627-084219](https://github.com/dakhnod/WatchAuthenticator/assets/174022863/ce39a5c3-2836-4686-b461-d45959a03f51)

**Comment by dakhnod** [comment]
Hmm, not quite sure what to do here. Looks like fossil abandoned their servers or something...

Not sure if disabling SSL is a good idea

**Comment by dakhnod** [comment]
try this one, but keep in mind that there is no SSL verification anymore. So an MITM might break the https.

https://github.com/dakhnod/WatchAuthenticator/releases/tag/v1.1

**Comment by buttnose** [comment]
Thank you for the update! It's definitely unfortunate that maintaining usability requires removing layers of security - and even more so that it's a direct result of Fossil's decision to abandon their user base. I appreciate your willingness to help us keep using our devices!

Update: I can confirm that it works like a charm!
